
[env]
CONFIG_ALACRITTY = "~/.config/alacritty/alacritty.toml"

[window]
# decorations = "None"
# blur = true
# opacity = 0.9

[font]
normal = { family = "JetBrainsMonoNerdFont", style = "Regular"}
size = 10

[general]

live_config_reload = true
import = [ "~/.config/alacritty/current_theme.toml" ]
